version: "3.0"

services:
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic_kibana
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.14.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic_kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  elastic_kibana:
    driver: bridge